### ISSUE TITLE
MAJOR ISSUE: [BufExplorer] buffer is not deleted on close of BufExplorer

### ISSUE THREAD

**Issue by jlanzarotta** [jlanzarotta/bufexplorer#110]
I am not 100% what happened, but for some reason the [BufExplorer] buffer is now, not being closed.  Also, if you forcefully close the [BufExplorer] buffer, strange things happen with the existing buffers.

This is a **major** issue, effecting version 7.4.25 all the way back to 7.4.2 and beyond.  I am not sure if something changed in Vim, but this is very odd, as bufexplorer is now unusable.

**HELP NEEDED** :)
I have not worked on .vim code in quite a number of years, so this is going to take a fair amount of time to fix, unless a .vim script guru can give me a hand at trying to fix this...

**Comment by basharh** [comment]
I think this is happening because `setlocal bufhidden=wipe` is not set in the [BufExplorer] buffer. 

As a result when you try to forcefully remove the [BufExplorer] using bufexplorer itself, you end up running `s:DeleteBuffer` which removes the [BufExplorer] buffer but then switches to another window and runs `setlocal nomodifiable`. That makes the previously unrelated window non-modifiable and thus the strange state.

**Comment by jlanzarotta** [comment]
Thanks for the patch.  I approved and merged it it.

What is odd is that I did not see this until I updated to the latest version of Vim 9.0 with patches.  Something must have changed since I was using a fairly old version.
